//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTUCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> IntakeDateID { get; set; }
        public Nullable<System.DateTime> SheduledDispatchDate { get; set; }
        public Nullable<int> DispatchDateID { get; set; }
        public Nullable<int> DrID { get; set; }
    
        public virtual DispatchDate DispatchDate { get; set; }
        public virtual EntryDate EntryDate { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
