//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTUCare
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTUCareDB : DbContext
    {
        public CTUCareDB()
            : base("name=CTUCareDB")
        {
        }
    
    	private static CTUCareDB instance;
    
    	public static CTUCareDB Instance
    	{
    		get
    		{
    			return instance ?? (instance = new CTUCareDB());
    		}
    	}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AdministeredMedicine> AdministeredMedicines { get; set; }
        public virtual DbSet<AdministeredProcedure> AdministeredProcedures { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<DispatchDate> DispatchDates { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<EntryDate> EntryDates { get; set; }
        public virtual DbSet<MedicalAid> MedicalAids { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Procedure> Procedures { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
