//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTUCampus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int StudentID { get; set; }
        public string studentName { get; set; }
        public string studentSurname { get; set; }
        public string studentIDNumber { get; set; }
        public int studentAge { get; set; }
        public string studentContactNumber { get; set; }
        public Nullable<int> studentParentID { get; set; }
        [Required]
        [Display(Name = "User name")]
        public string studentUserName { get; set; }
        [Required]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string studentPassword { get; set; }
    
        public virtual Parent Parent { get; set; }
    }
}
